### PR TITLE
Catch nil values for performance from Controllr API

### PR DESCRIPTION
**Pull request by toupeira**
Fixes https://sentry.panter.biz/panter/apipanterch/issues/5862/

The accounting data only goes back to October 2012, on requests for older months [no performance is returned](https://git.panter.ch/panter/controllr/blob/master/app/controllers/api/monthly_salaries_controller.rb).

### CODE REVIEW

**Comment by koffeinfrei** [comment]
But the old api used to return data on this: https://api.panter.ch/performance?start_date=2012-09-01&end_date=2012-10-01

Has the controller changed such that it doesn't have any data at all anymore for those older dates?

**Comment by toupeira** [comment]
@koffeinfrei hmm that's probably caused by this change: https://git.panter.ch/panter/controllr/commit/69cf2169

Previously the calculation used the `entries` directly (which go back until 2004), but in https://git.panter.ch/panter/controllr/merge_requests/168 I changed this to go through the `accounting_months` to DRY it up, and it looks like that table didn't exist before October 2012 ;-)

Do we need to do something about this, i.e. does the API still try to update the old performance values or can we just keep using the old stored values?

**Comment by koffeinfrei** [comment]
> Do we need to do something about this, i.e. does the API still try to update the old performance values or can we just keep using the old stored values?

The old values will stay in redis, so a query for those dates will still return them. The data fetcher does not try to update them if they don't exist anymore in the source (i.e. controllr).

We may want to delete those values from redis...

**Comment by toupeira** [comment]
> We may want to delete those values from redis...

@koffeinfrei ok I don't mind keeping them, because they should still be correct.

**Comment by koffeinfrei** [comment]
> @koffeinfrei ok I don't mind keeping them, because they should still be correct.

Then we should update the controllr to return that data again. Otherwise we just have some random legacy data in the redis cache... The data should be reproducible, otherwise it's confusing and inconsistent with the data source.

I'll truncate the redis data when this fix has been deployed.

**Comment by toupeira** [comment]
@koffeinfrei ok sounds good to me!

The fix is deployed now.

**Comment by koffeinfrei** [comment]
@toupeira Data cleared and re-fetched

**Pull request merged**
